- name: "🔴 red"
  color: "db5855"
- name: "🟠 orange"
  color: "F05138"
- name: "🟡 yellow"
  color: "f1e05a"
- name: "🟢 green"
  color: "89e051"
- name: "🔵 blue"
  color: "00ADD8"
- name: "🟣 violet"
  color: "3178c6"
